from_l1=str(input("enter from address name:"))
from_l2=str(input("enter from address door no:"))
from_l3=str(input("enter from address street:"))
from_l4=str(input("enter from address city:"))
from_l5=str(input("enter from address state:"))
to_l1=str(input("enter to address name/post:"))
to_l2=str(input("enter to address school:"))
to_l3=str(input("enter to address district:"))
sir_madam=str(input("sir/madam:"))
no_of_days=int(input("no of days:"))
place=str(input("enter place"))
date=str(input("enter date"))
name=str(input("enter name:"))
print()
print("FROM")
print()
print(from_l1)
print(from_l2)
print(from_l3)
print(from_l4)
print(from_l5)
print()
print("TO")
print()
print(to_l1)
print(to_l2)
print(to_l3)
print()
print("Respected ",sir_madam)
print("\tAs I was suffering from fever, I'm not able to attend the class. So, Kindly grant me leave for ",no_of_days," days.")
print()
print("\tThanking you")
print()
print("Place:",place,"\tYours faithfully,")
print("Date:",date,"\t",name)
