##relational operators:
a=int(input("Enter the value of a"))
b=int(input("Enter the value of b"))
print("---Relational Operator---")
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
print(a==b)
print(a!=b)
##logical operator:
print("---Logical Operator---")
print((a>b)and(a==b))
print((a<b)and(a<=b))
print((a<b)or(a>b))
print(not((a>b)and(a>b)))
