print(" *"*4)
print(" *"+" "*5+"*")
print(" *"+" "*5+"*")
print(" *"*4)
print()
print("   *")
print(" *   *")
print("*     *")
print(" *   *")
print("   *")
print()
print("    *  *")
print("  *  *  *")
print("  *     *")
print("   *   *")
print("     *")
print()
print("     *  *  *")
print("   *         *")
print(" *            *")
print("*              *")
print("*              *")
print(" *            * ")
print("   *        *")
print("     *    *")
print("       *")
