print("▬"*42)
print(" S.NO |\tNAME   | AGE |\tE-MAIL ID\t |")
print("▬"*42)
print("  1   |\tAlan   | 20  |\talan@gmail.com\t |")
print("  2   |\tHarish | 19  |\tharish@gmail.com |")
print("  3   |\tNithish| 25  |\tnithish@gmail.com|")
print("▬"*42)
